name: tests

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: '14 3 * * 1'  # at 03:14 on Monday.

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.13"
          - "3.12"
          - "3.11"
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install rclone
        run: |
          sudo -v ; curl https://rclone.org/install.sh | sudo bash
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Pytest
        run: |
          uv run python --version
          uv run pytest --cov --junitxml=junit.xml -o junit_family=legacy
    #   - name: Upload coverage to Codecov
    #     uses: codecov/codecov-action@v5
    #     with:
    #       token: ${{ secrets.CODECOV_TOKEN }}
    #   - name: Upload test results to Codecov
    #     if: ${{ !cancelled() }}
    #     uses: codecov/test-results-action@v1
    #     with:
    #       token: ${{ secrets.CODECOV_TOKEN }}
